import type { TemplateDefinition } from "./types.js";

export const OFFICIAL_TEMPLATES: TemplateDefinition[] = [
  {
    id: "minimal",
    name: "Minimal Next.js",
    description: "Lean, clean Next.js application with TypeScript, Tailwind CSS, shadcn UI, and Vitest",
    category: "starter",
    presetId: "minimal",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: ["Next.js App Router", "TypeScript", "Tailwind CSS", "shadcn UI", "Vitest"],
    aliases: ["default"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "saas",
    name: "SaaS Application",
    description: "Production-ready SaaS with Drizzle ORM, Better Auth, transactional email, storage, billing-ready architecture, and testing",
    category: "saas",
    presetId: "saas",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Authentication (Better Auth)",
      "Database & Migrations (Drizzle ORM)",
      "Transactional Email (React Email + Mailpit)",
      "File Uploads (Storage Abstraction)",
      "Billing Architecture (Payments Abstraction)",
      "Data Fetching (TanStack Query)",
      "Observability (Sentry)",
      "Security Headers & Health Endpoints",
      "Testing (Vitest + Playwright)",
    ],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "admin",
    name: "Admin Dashboard",
    description: "Enterprise administration dashboard with authentication, interactive TanStack tables, Recharts visualizations, and client state",
    category: "dashboard",
    presetId: "admin",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Authentication (Better Auth)",
      "Database Layer (Drizzle ORM)",
      "Advanced Data Tables (TanStack Table)",
      "Interactive Visualizations (Recharts)",
      "Query Caching (TanStack Query)",
      "Client Store (Zustand)",
      "Testing (Vitest + Playwright)",
    ],
    aliases: ["dashboard"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "ecommerce",
    name: "E-commerce Platform",
    description: "Full-stack e-commerce starter with product catalog, cart state, orders table, storage, and payment checkout architecture",
    category: "ecommerce",
    presetId: "ecommerce",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Authentication & Customer Accounts (Better Auth)",
      "Database & Products Schema (Drizzle ORM)",
      "Cart & Filter State (Zustand)",
      "Order Management Tables (TanStack Table)",
      "Checkout & Billing Abstraction (Payments)",
      "Product Media Uploads (Storage)",
      "Testing (Vitest + Playwright)",
    ],
    aliases: ["store"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "blog",
    name: "Blog & CMS",
    description: "Content publishing application with Tiptap rich text editor, content management tables, uploads, and data fetching",
    category: "content",
    presetId: "blog",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Author & User Auth (Better Auth)",
      "Post & Taxonomy Schema (Drizzle ORM)",
      "Rich Text Content Editor (Tiptap)",
      "Post Management Tables (TanStack Table)",
      "Cover Image Uploads (Storage)",
      "Data Caching (TanStack Query)",
      "Testing (Vitest)",
    ],
    aliases: ["cms"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "ai",
    name: "AI Application",
    description: "Conversational AI platform with Vercel AI SDK, multi-model streaming (OpenAI, Claude, Ollama), storage, and chat interface",
    category: "ai",
    presetId: "ai",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Vercel AI SDK Core & React Hooks",
      "Model Provider Integrations (OpenAI, Anthropic, Ollama)",
      "User Authentication (Better Auth)",
      "Document/Attachment Uploads (Storage)",
      "Chat State & History (Zustand)",
      "Data Fetching (TanStack Query)",
      "Testing (Vitest)",
    ],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "api",
    name: "API Starter",
    description: "Headless microservice backend with tRPC type-safe procedures, OpenAPI contracts, Docker, and health check probes",
    category: "api",
    presetId: "api",
    defaultUiLibrary: "headless",
    structure: "nextjs",
    features: [
      "Type-safe Endpoints (tRPC)",
      "OpenAPI Specification & Types (OpenAPI Client)",
      "Production Containerization (Docker)",
      "Liveness & Readiness Endpoints (Health)",
      "Testing (Vitest)",
    ],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "realtime",
    name: "Real-time Application",
    description: "Live interactive application with Server-Sent Events (SSE), presence & notifications, Redis caching, and state",
    category: "realtime",
    presetId: "realtime",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Server-Sent Events & Live Streaming (Realtime)",
      "User Authentication (Better Auth)",
      "Data Persistence (Drizzle ORM)",
      "In-Memory Cache (Redis)",
      "Real-time UI State (Zustand)",
      "Query Invalidation (TanStack Query)",
      "Testing (Vitest)",
    ],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "react-native",
    name: "React Native Mobile",
    description: "Cross-platform mobile application powered by Expo SDK 52 and React Native 0.76 with TypeScript and navigation",
    category: "mobile",
    defaultUiLibrary: "headless",
    structure: "react-native",
    features: [
      "Expo SDK 52 & React Native 0.76",
      "TypeScript & Strict Configuration",
      "Theme Tokens & Safe Area Contexts",
      "Native UI Primitives & Card/Button Components",
      "Cross-Platform API Service Client",
    ],
    aliases: ["mobile", "expo"],
    compatibility: {
      node: ">=18.18.0",
    },
  },
];
