import type { TemplateDefinition } from "./types.js";

export const OFFICIAL_TEMPLATES: TemplateDefinition[] = [
  {
    id: "minimal",
    name: "Minimal Next.js",
    description: "Lean, clean Next.js application with TypeScript, Tailwind CSS, shadcn UI, Vitest, and Husky git hooks",
    category: "starter",
    presetId: "minimal",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: ["Next.js App Router", "TypeScript", "Tailwind CSS", "shadcn UI", "Vitest", "Husky + lint-staged Git Hooks"],
    aliases: ["default"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "saas",
    name: "SaaS Application",
    description: "Production-ready SaaS with Drizzle ORM, Better Auth, transactional email, storage, billing-ready architecture, testing, and Husky git hooks",
    category: "saas",
    presetId: "saas",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Authentication (Better Auth)",
      "Database & Migrations (Drizzle ORM)",
      "Transactional Email (React Email + Mailpit)",
      "File Uploads (Storage Abstraction)",
      "Billing Architecture (Payments Abstraction)",
      "Data Fetching (TanStack Query)",
      "Observability (Sentry)",
      "Security Headers & Health Endpoints",
      "Testing (Vitest + Playwright)",
      "Git Hooks (Husky + lint-staged)",
    ],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "admin",
    name: "Admin Dashboard",
    description: "Enterprise administration dashboard with authentication, interactive TanStack tables, Recharts visualizations, client state, and Husky git hooks",
    category: "dashboard",
    presetId: "admin",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Authentication (Better Auth)",
      "Database Layer (Drizzle ORM)",
      "Advanced Data Tables (TanStack Table)",
      "Interactive Visualizations (Recharts)",
      "Query Caching (TanStack Query)",
      "Client Store (Zustand)",
      "Testing (Vitest + Playwright)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["dashboard"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "ecommerce",
    name: "E-commerce Platform",
    description: "Full-stack e-commerce starter with product catalog, cart state, orders table, storage, payment checkout architecture, and Husky git hooks",
    category: "ecommerce",
    presetId: "ecommerce",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Authentication & Customer Accounts (Better Auth)",
      "Database & Products Schema (Drizzle ORM)",
      "Cart & Filter State (Zustand)",
      "Order Management Tables (TanStack Table)",
      "Checkout & Billing Abstraction (Payments)",
      "Product Media Uploads (Storage)",
      "Testing (Vitest + Playwright)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["store"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "blog",
    name: "Blog & CMS",
    description: "Content publishing application with Tiptap rich text editor, content management tables, uploads, data fetching, and Husky git hooks",
    category: "content",
    presetId: "blog",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Author & User Auth (Better Auth)",
      "Post & Taxonomy Schema (Drizzle ORM)",
      "Rich Text Content Editor (Tiptap)",
      "Post Management Tables (TanStack Table)",
      "Cover Image Uploads (Storage)",
      "Data Caching (TanStack Query)",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["cms"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "ai",
    name: "AI Application",
    description: "Conversational AI platform with Vercel AI SDK, multi-model streaming (OpenAI, Claude, Ollama), storage, chat interface, and Husky git hooks",
    category: "ai",
    presetId: "ai",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Vercel AI SDK Core & React Hooks",
      "Model Provider Integrations (OpenAI, Anthropic, Ollama)",
      "User Authentication (Better Auth)",
      "Document/Attachment Uploads (Storage)",
      "Chat State & History (Zustand)",
      "Data Fetching (TanStack Query)",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "api",
    name: "API Starter",
    description: "Headless microservice backend with tRPC type-safe procedures, OpenAPI contracts, Docker, health check probes, and Husky git hooks",
    category: "api",
    presetId: "api",
    defaultUiLibrary: "headless",
    structure: "nextjs",
    features: [
      "Type-safe Endpoints (tRPC)",
      "OpenAPI Specification & Types (OpenAPI Client)",
      "Production Containerization (Docker)",
      "Liveness & Readiness Endpoints (Health)",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "realtime",
    name: "Real-time Application",
    description: "Live interactive application with Server-Sent Events (SSE), presence & notifications, Redis caching, state, and Husky git hooks",
    category: "realtime",
    presetId: "realtime",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Server-Sent Events & Live Streaming (Realtime)",
      "User Authentication (Better Auth)",
      "Data Persistence (Drizzle ORM)",
      "In-Memory Cache (Redis)",
      "Real-time UI State (Zustand)",
      "Query Invalidation (TanStack Query)",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "react-native",
    name: "React Native Mobile",
    description: "Cross-platform mobile application powered by Expo SDK 52 and React Native 0.76 with TypeScript and navigation",
    category: "mobile",
    defaultUiLibrary: "headless",
    structure: "react-native",
    features: [
      "Expo SDK 52 & React Native 0.76",
      "TypeScript & Strict Configuration",
      "Theme Tokens & Safe Area Contexts",
      "Native UI Primitives & Card/Button Components",
      "Cross-Platform API Service Client",
    ],
    aliases: ["mobile", "expo"],
    compatibility: {
      node: ">=18.18.0",
    },
  },
  {
    id: "multi-tenant",
    name: "B2B Multi-Tenant Platform",
    description: "Enterprise SaaS starter with organization tenancies, billing tiers, member data tables, transactional email, and Playwright tests",
    category: "saas",
    presetId: "multi-tenant",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Multi-tenant Organization Architecture",
      "Authentication & Roles (Better Auth)",
      "Database & Tenancy Schema (Drizzle ORM)",
      "Payment & Subscription Tiers (Payments)",
      "Transactional Email Notifications (React Email)",
      "Data Grid with Pagination & Filtering (TanStack Table)",
      "Server State Management (TanStack Query)",
      "Client State Store (Zustand)",
      "Testing (Vitest + Playwright)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["b2b-saas", "multitenant", "b2b"],
    infrastructure: {
      recommendedProvider: "kubernetes",
      profile: "production",
    },
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "supabase",
    name: "Supabase Fullstack Application",
    description: "Full-stack application powered by Supabase Auth, PostgreSQL database, Realtime subscriptions, and Storage uploads",
    category: "app",
    presetId: "supabase",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Supabase SSR Authentication",
      "PostgreSQL Client & Database (Supabase)",
      "Live Realtime Subscriptions (Supabase Realtime)",
      "File & Media Uploads (Supabase Storage)",
      "Data Caching (TanStack Query)",
      "Interactive Data Tables (TanStack Table)",
      "Client Store (Zustand)",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["supabase-starter", "supabase-app"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "ai-agent",
    name: "AI Agent & RAG Knowledge Engine",
    description: "Multi-model autonomous AI Agent and RAG system with Vercel AI SDK, OpenAI/Claude routing, document ingestion, vector storage, and chat history",
    category: "ai",
    presetId: "ai-agent",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Vercel AI SDK Core & React Hooks",
      "Multi-Provider Streaming (OpenAI + Anthropic)",
      "Document Ingestion & File Storage",
      "Vector & Knowledge Database (Drizzle ORM)",
      "Chat Sessions & History (Zustand)",
      "Data Caching (TanStack Query)",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["rag", "agent"],
    infrastructure: {
      recommendedProvider: "kubernetes",
      profile: "standard",
    },
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "graphql-api",
    name: "GraphQL API Microservice",
    description: "Headless GraphQL backend with schema-first codegen, Drizzle ORM, Redis caching layer, Docker containerization, and health check probes",
    category: "api",
    presetId: "graphql-api",
    defaultUiLibrary: "headless",
    structure: "nextjs",
    features: [
      "GraphQL Yoga Server & Schema Execution",
      "Type-Safe Codegen & Query Client",
      "Database & Migrations (Drizzle ORM)",
      "In-Memory Caching & Rate Limiting (Redis)",
      "Container Infrastructure (Docker)",
      "Liveness & Readiness Endpoints (Health)",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["graphql", "apollo"],
    infrastructure: {
      recommendedProvider: "docker",
      profile: "standard",
    },
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "design-system",
    name: "Design System & Component Catalog",
    description: "Component workshop and design tokens library with Storybook, Framer Motion animations, token definitions, and component unit tests",
    category: "ui",
    presetId: "design-system",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Interactive Component Workshop (Storybook)",
      "Design System Tokens & Utilities",
      "Framer Motion Animations & Motion Variants",
      "shadcn UI Foundation & Primitives",
      "Component Unit & Snapshot Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["components", "storybook", "ui-kit"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "pwa",
    name: "Progressive Web App (PWA)",
    description: "Offline-capable Progressive Web App with service worker caching, app manifest, persistent local state, and mobile-optimized UI",
    category: "mobile",
    presetId: "pwa",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Progressive Web App Service Worker (PWA)",
      "App Manifest & Offline Caching Strategies",
      "Persistent Client State (Zustand)",
      "Optimistic Data Fetching (TanStack Query)",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["offline-first", "pwa-app"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "docs",
    name: "Documentation & Knowledge Base",
    description: "Developer documentation portal with Tiptap rich content editor, search indexing, dark mode, queries, and unit tests",
    category: "content",
    presetId: "docs",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Rich Content Editor & Renderer (Tiptap)",
      "Interactive Documentation Layout & Navigation",
      "Search & Indexing Queries (TanStack Query)",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["documentation", "knowledgebase", "wiki"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "mobile-fullstack",
    name: "Mobile + Web Fullstack Companion",
    description: "Type-safe fullstack backend companion for React Native / Expo mobile with tRPC, auth, and database",
    category: "app",
    presetId: "mobile-fullstack",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Type-Safe tRPC API Endpoints",
      "User Authentication & Sessions (Better Auth)",
      "Database & Migrations (Drizzle ORM)",
      "Data Caching (TanStack Query)",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["cross-platform", "mobile-web"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
  {
    id: "portfolio",
    name: "Developer Portfolio & Showcase",
    description: "Modern personal showcase with smooth animations, custom design tokens, and testing",
    category: "showcase",
    presetId: "portfolio",
    defaultUiLibrary: "shadcn",
    structure: "nextjs",
    features: [
      "Framer Motion Transitions & Animations",
      "Design System Tokens & Themes",
      "Project Showcase & Contact Components",
      "Testing (Vitest)",
      "Git Hooks (Husky + lint-staged)",
    ],
    aliases: ["showcase", "resume"],
    compatibility: {
      node: ">=18.18.0",
      next: ">=15.0.0",
      react: ">=19.0.0",
    },
  },
];
