import type { PresetDefinition } from "./types.js";

export const OFFICIAL_PRESETS: PresetDefinition[] = [
  {
    id: "minimal",
    name: "Minimal Next.js",
    description: "Lean, clean Next.js starter with TypeScript, Tailwind CSS, unit testing, and git hooks",
    category: "starter",
    defaultUiLibrary: "shadcn",
    plugins: ["vitest", "husky"],
  },
  {
    id: "fullstack",
    name: "Fullstack Application",
    description: "Production fullstack Next.js with Drizzle ORM, Better Auth, tRPC, Query, E2E testing, and git hooks",
    category: "app",
    defaultUiLibrary: "shadcn",
    plugins: [
      "drizzle",
      "betterAuth",
      "trpc",
      "tanstackQuery",
      "vitest",
      "playwright",
      "husky",
    ],
  },
  {
    id: "saas",
    name: "SaaS Starter",
    description: "Complete SaaS starter with database, auth, email, storage, billing-ready, monitoring, security, and git hooks",
    category: "saas",
    defaultUiLibrary: "shadcn",
    plugins: [
      "drizzle",
      "betterAuth",
      "tanstackQuery",
      "sentry",
      "reactEmail",
      "storage",
      "payments",
      "dockerCompose",
      "securityHeaders",
      "health",
      "vitest",
      "playwright",
      "husky",
    ],
  },
  {
    id: "admin",
    name: "Admin Dashboard",
    description: "Enterprise admin dashboard with auth, data tables, charting, state management, testing, and git hooks",
    category: "dashboard",
    defaultUiLibrary: "shadcn",
    plugins: [
      "betterAuth",
      "drizzle",
      "tanstackTable",
      "recharts",
      "tanstackQuery",
      "zustand",
      "vitest",
      "playwright",
      "husky",
    ],
  },
  {
    id: "dashboard",
    name: "Analytics Dashboard",
    description: "Data-heavy dashboard with TanStack Tables, Recharts charts, Query caching, state, testing, and git hooks",
    category: "analytics",
    defaultUiLibrary: "shadcn",
    plugins: [
      "tanstackTable",
      "recharts",
      "tanstackQuery",
      "zustand",
      "vitest",
      "husky",
    ],
  },
  {
    id: "ecommerce",
    name: "E-commerce Platform",
    description: "Online store starter with catalog tables, cart state, checkout/payments architecture, storage, and git hooks",
    category: "ecommerce",
    defaultUiLibrary: "shadcn",
    plugins: [
      "drizzle",
      "betterAuth",
      "tanstackTable",
      "tanstackQuery",
      "zustand",
      "payments",
      "storage",
      "vitest",
      "playwright",
      "husky",
    ],
  },
  {
    id: "blog",
    name: "Blog & CMS",
    description: "Content management platform with rich text editor, content tables, uploads, queries, and git hooks",
    category: "content",
    defaultUiLibrary: "shadcn",
    plugins: [
      "drizzle",
      "betterAuth",
      "tiptap",
      "tanstackTable",
      "storage",
      "tanstackQuery",
      "vitest",
      "husky",
    ],
  },
  {
    id: "ai",
    name: "AI & LLM Application",
    description: "AI streaming app with Vercel AI SDK, OpenAI model integration, storage, state management, and git hooks",
    category: "ai",
    defaultUiLibrary: "shadcn",
    plugins: [
      "ai",
      "openai",
      "betterAuth",
      "storage",
      "tanstackQuery",
      "zustand",
      "vitest",
      "husky",
    ],
  },
  {
    id: "api",
    name: "API & Microservice",
    description: "Type-safe API backend with tRPC, OpenAPI validation, Docker containerization, health checks, and git hooks",
    category: "api",
    defaultUiLibrary: "headless",
    plugins: [
      "trpc",
      "openapi",
      "docker",
      "health",
      "vitest",
      "husky",
    ],
  },
  {
    id: "realtime",
    name: "Real-time Application",
    description: "Live streaming events, real-time presence/notifications, database, caching, state, and git hooks",
    category: "realtime",
    defaultUiLibrary: "shadcn",
    plugins: [
      "realtime",
      "betterAuth",
      "drizzle",
      "redis",
      "zustand",
      "tanstackQuery",
      "vitest",
      "husky",
    ],
  },
];
